-- Local seed data. Runs after all migrations on the first `supabase start` and on every
-- `supabase db reset`. Data only, never DDL. Reference data is seeded by migrations; synthetic
-- datasets are loaded with `pnpm synth:small` (see docs/synthetic-data.md), not from this file.
