"""Emits the reference-data INSERT statements embedded in the reference_data migration.

The package CSVs under ``maqdar_engine/synth/data`` are the single source of truth for countries,
currencies, Ramadan/Eid windows and public holidays. The migration embeds the output of
``emit()`` between ``BEGIN_MARK`` and ``END_MARK``; ``tests/test_reference_sql_in_sync.py`` fails
when the two drift apart.
"""

from __future__ import annotations

import csv
from importlib import resources
from typing import Iterable

BEGIN_MARK = "-- <<< reference data generated by `maqdar-synth emit-reference-sql` (do not edit by hand)"
END_MARK = "-- >>> end of generated reference data"


def load_rows(name: str) -> list[dict[str, str]]:
    """Reads a package CSV as a list of dicts, preserving file order."""
    data_dir = resources.files("maqdar_engine.synth") / "data"
    with (data_dir / name).open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def quote(value: str | None) -> str:
    """Renders a text value as a SQL literal; empty strings become NULL."""
    if value is None or value == "":
        return "null"
    return "'" + value.replace("'", "''") + "'"


def number(value: str) -> str:
    if value == "":
        return "null"
    float(value)  # validates
    return value


def date(value: str) -> str:
    if value == "":
        return "null"
    year, month, day = value.split("-")
    assert len(year) == 4 and len(month) == 2 and len(day) == 2, value
    return f"'{value}'"


def smallint_array(value: str) -> str:
    parts = [p.strip() for p in value.split(";") if p.strip()]
    for part in parts:
        assert part.isdigit() and 1 <= int(part) <= 7, value
    return "'{" + ",".join(parts) + "}'::smallint[]"


def _values(rows: Iterable[tuple[str, ...]]) -> str:
    return ",\n".join("  (" + ", ".join(row) + ")" for row in rows)


def emit() -> str:
    """Returns the SQL block for the migration (without the markers)."""
    currencies = load_rows("currencies.csv")
    countries = load_rows("countries.csv")
    windows = load_rows("ramadan_windows.csv")
    holidays = load_rows("public_holidays.csv")

    blocks: list[str] = []

    blocks.append(
        "insert into public.currencies (code, name_en, name_ar, minor_units) values\n"
        + _values(
            (quote(r["code"]), quote(r["name_en"]), quote(r["name_ar"]), number(r["minor_units"]))
            for r in currencies
        )
        + ";"
    )

    blocks.append(
        "insert into public.countries (code, name_en, name_ar, currency_code, weekend_days, vat_rate, "
        "timezone, utc_offset_minutes, holiday_coverage_from, holiday_coverage_to) values\n"
        + _values(
            (
                quote(r["code"]),
                quote(r["name_en"]),
                quote(r["name_ar"]),
                quote(r["currency_code"]),
                smallint_array(r["weekend_days"]),
                number(r["vat_rate"]),
                quote(r["timezone"]),
                number(r["utc_offset_minutes"]),
                date(r["holiday_coverage_from"]),
                date(r["holiday_coverage_to"]),
            )
            for r in countries
        )
        + ";"
    )

    blocks.append(
        "insert into public.ramadan_windows (country_code, hijri_year, ramadan_start, ramadan_end, "
        "eid_al_fitr, arafat_day, eid_al_adha, source) values\n"
        + _values(
            (
                quote(r["country_code"]),
                number(r["hijri_year"]),
                date(r["ramadan_start"]),
                date(r["ramadan_end"]),
                date(r["eid_al_fitr"]),
                date(r["arafat_day"]),
                date(r["eid_al_adha"]),
                quote(r["source"]),
            )
            for r in windows
        )
        + ";"
    )

    blocks.append(
        "insert into public.public_holidays (country_code, holiday_date, name_en, kind, sector, "
        "shifted_from, source, note) values\n"
        + _values(
            (
                quote(r["country_code"]),
                date(r["holiday_date"]),
                quote(r["name_en"]),
                quote(r["kind"]),
                quote(r["sector"]),
                date(r["shifted_from"]),
                quote(r["source"]),
                quote(r["note"]),
            )
            for r in holidays
        )
        + ";"
    )

    return "\n\n".join(blocks) + "\n"


def render_with_marks() -> str:
    return f"{BEGIN_MARK}\n{emit()}{END_MARK}\n"


def extract_generated_block(migration_sql: str) -> str:
    """Returns the text between the markers in a migration file (without the marker lines)."""
    start = migration_sql.index(BEGIN_MARK) + len(BEGIN_MARK) + 1
    end = migration_sql.index(END_MARK)
    return migration_sql[start:end]


if __name__ == "__main__":  # pragma: no cover
    import sys

    sys.stdout.write(render_with_marks())
