// Generated by `pnpm db:types` from the local Supabase schema. Do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  
  "public": {
          Tables: {
            "countries": {
                  Row: {
                    "code": string,"currency_code": string,"holiday_coverage_from": string | null,"holiday_coverage_to": string | null,"name_ar": string | null,"name_en": string,"timezone": string,"utc_offset_minutes": number,"vat_rate": number,"weekend_days": (number)[]
                  }
                  ComputedFields: never
                  Insert: {
                    "code": string,"currency_code": string,"holiday_coverage_from"?: string | null,"holiday_coverage_to"?: string | null,"name_ar"?: string | null,"name_en": string,"timezone": string,"utc_offset_minutes": number,"vat_rate": number,"weekend_days": (number)[]
                  }
                  Update: {
                    "code"?: string,"currency_code"?: string,"holiday_coverage_from"?: string | null,"holiday_coverage_to"?: string | null,"name_ar"?: string | null,"name_en"?: string,"timezone"?: string,"utc_offset_minutes"?: number,"vat_rate"?: number,"weekend_days"?: (number)[]
                  }
                  Relationships: [
                    {
      foreignKeyName: "countries_currency_code_fkey"
      columns: ["currency_code"]
isOneToOne: false
      referencedRelation: "currencies"
      referencedColumns: ["code"]
    }
                  ]
                },"currencies": {
                  Row: {
                    "code": string,"minor_units": number,"name_ar": string | null,"name_en": string
                  }
                  ComputedFields: never
                  Insert: {
                    "code": string,"minor_units": number,"name_ar"?: string | null,"name_en": string
                  }
                  Update: {
                    "code"?: string,"minor_units"?: number,"name_ar"?: string | null,"name_en"?: string
                  }
                  Relationships: [
                    
                  ]
                },"demand_history": {
                  Row: {
                    "demand_date": string,"item_id": string,"location_id": string,"lost_sales_quantity": number,"organization_id": string,"quantity": number
                  }
                  ComputedFields: never
                  Insert: {
                    "demand_date": string,"item_id": string,"location_id": string,"lost_sales_quantity"?: number,"organization_id": string,"quantity"?: number
                  }
                  Update: {
                    "demand_date"?: string,"item_id"?: string,"location_id"?: string,"lost_sales_quantity"?: number,"organization_id"?: string,"quantity"?: number
                  }
                  Relationships: [
                    
                  ]
                },"item_supersessions": {
                  Row: {
                    "created_at": string,"effective_on": string,"id": string,"note": string | null,"organization_id": string,"predecessor_item_id": string,"quantity_factor": number,"successor_item_id": string,"updated_at": string
                  }
                  ComputedFields: never
                  Insert: {
                    "created_at"?: string,"effective_on": string,"id"?: string,"note"?: string | null,"organization_id": string,"predecessor_item_id": string,"quantity_factor"?: number,"successor_item_id": string,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"effective_on"?: string,"id"?: string,"note"?: string | null,"organization_id"?: string,"predecessor_item_id"?: string,"quantity_factor"?: number,"successor_item_id"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "item_supersessions_organization_id_fkey"
      columns: ["organization_id"]
isOneToOne: false
      referencedRelation: "organizations"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "item_supersessions_organization_id_predecessor_item_id_fkey"
      columns: ["organization_id","predecessor_item_id"]
isOneToOne: false
      referencedRelation: "items"
      referencedColumns: ["organization_id","id"]
    },{
      foreignKeyName: "item_supersessions_organization_id_successor_item_id_fkey"
      columns: ["organization_id","successor_item_id"]
isOneToOne: false
      referencedRelation: "items"
      referencedColumns: ["organization_id","id"]
    }
                  ]
                },"items": {
                  Row: {
                    "brand": string | null,"code": string,"created_at": string,"currency": string,"discontinued_on": string | null,"id": string,"introduced_on": string | null,"name_ar": string | null,"name_en": string,"organization_id": string,"product_group": string,"status": string,"unit_cost": number,"unit_of_measure": string,"updated_at": string
                  }
                  ComputedFields: never
                  Insert: {
                    "brand"?: string | null,"code": string,"created_at"?: string,"currency": string,"discontinued_on"?: string | null,"id"?: string,"introduced_on"?: string | null,"name_ar"?: string | null,"name_en": string,"organization_id": string,"product_group": string,"status"?: string,"unit_cost": number,"unit_of_measure": string,"updated_at"?: string
                  }
                  Update: {
                    "brand"?: string | null,"code"?: string,"created_at"?: string,"currency"?: string,"discontinued_on"?: string | null,"id"?: string,"introduced_on"?: string | null,"name_ar"?: string | null,"name_en"?: string,"organization_id"?: string,"product_group"?: string,"status"?: string,"unit_cost"?: number,"unit_of_measure"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "items_currency_fkey"
      columns: ["currency"]
isOneToOne: false
      referencedRelation: "currencies"
      referencedColumns: ["code"]
    },{
      foreignKeyName: "items_organization_id_fkey"
      columns: ["organization_id"]
isOneToOne: false
      referencedRelation: "organizations"
      referencedColumns: ["id"]
    }
                  ]
                },"locations": {
                  Row: {
                    "city": string | null,"code": string,"country_code": string,"created_at": string,"id": string,"is_active": boolean,"latitude": number | null,"location_type": string,"longitude": number | null,"name_ar": string | null,"name_en": string,"organization_id": string,"parent_location_id": string | null,"timezone": string,"updated_at": string
                  }
                  ComputedFields: never
                  Insert: {
                    "city"?: string | null,"code": string,"country_code": string,"created_at"?: string,"id"?: string,"is_active"?: boolean,"latitude"?: number | null,"location_type": string,"longitude"?: number | null,"name_ar"?: string | null,"name_en": string,"organization_id": string,"parent_location_id"?: string | null,"timezone": string,"updated_at"?: string
                  }
                  Update: {
                    "city"?: string | null,"code"?: string,"country_code"?: string,"created_at"?: string,"id"?: string,"is_active"?: boolean,"latitude"?: number | null,"location_type"?: string,"longitude"?: number | null,"name_ar"?: string | null,"name_en"?: string,"organization_id"?: string,"parent_location_id"?: string | null,"timezone"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "locations_country_code_fkey"
      columns: ["country_code"]
isOneToOne: false
      referencedRelation: "countries"
      referencedColumns: ["code"]
    },{
      foreignKeyName: "locations_organization_id_fkey"
      columns: ["organization_id"]
isOneToOne: false
      referencedRelation: "organizations"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "locations_organization_id_parent_location_id_fkey"
      columns: ["organization_id","parent_location_id"]
isOneToOne: false
      referencedRelation: "locations"
      referencedColumns: ["organization_id","id"]
    }
                  ]
                },"membership_locations": {
                  Row: {
                    "created_at": string,"location_id": string,"organization_id": string,"user_id": string
                  }
                  ComputedFields: never
                  Insert: {
                    "created_at"?: string,"location_id": string,"organization_id": string,"user_id": string
                  }
                  Update: {
                    "created_at"?: string,"location_id"?: string,"organization_id"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "membership_locations_organization_id_location_id_fkey"
      columns: ["organization_id","location_id"]
isOneToOne: false
      referencedRelation: "locations"
      referencedColumns: ["organization_id","id"]
    },{
      foreignKeyName: "membership_locations_organization_id_user_id_fkey"
      columns: ["organization_id","user_id"]
isOneToOne: false
      referencedRelation: "memberships"
      referencedColumns: ["organization_id","user_id"]
    }
                  ]
                },"memberships": {
                  Row: {
                    "created_at": string,"organization_id": string,"role": string,"updated_at": string,"user_id": string
                  }
                  ComputedFields: never
                  Insert: {
                    "created_at"?: string,"organization_id": string,"role": string,"updated_at"?: string,"user_id": string
                  }
                  Update: {
                    "created_at"?: string,"organization_id"?: string,"role"?: string,"updated_at"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "memberships_organization_id_fkey"
      columns: ["organization_id"]
isOneToOne: false
      referencedRelation: "organizations"
      referencedColumns: ["id"]
    }
                  ]
                },"organization_invitations": {
                  Row: {
                    "accepted_at": string | null,"accepted_by": string | null,"created_at": string,"email": string,"expires_at": string,"id": string,"invited_by": string | null,"last_sent_at": string,"organization_id": string,"revoked_at": string | null,"revoked_by": string | null,"role": string,"send_count": number
                  }
                  ComputedFields: never
                  Insert: {
                    "accepted_at"?: string | null,"accepted_by"?: string | null,"created_at"?: string,"email": string,"expires_at"?: string,"id"?: string,"invited_by"?: string | null,"last_sent_at"?: string,"organization_id": string,"revoked_at"?: string | null,"revoked_by"?: string | null,"role": string,"send_count"?: number
                  }
                  Update: {
                    "accepted_at"?: string | null,"accepted_by"?: string | null,"created_at"?: string,"email"?: string,"expires_at"?: string,"id"?: string,"invited_by"?: string | null,"last_sent_at"?: string,"organization_id"?: string,"revoked_at"?: string | null,"revoked_by"?: string | null,"role"?: string,"send_count"?: number
                  }
                  Relationships: [
                    {
      foreignKeyName: "organization_invitations_organization_id_fkey"
      columns: ["organization_id"]
isOneToOne: false
      referencedRelation: "organizations"
      referencedColumns: ["id"]
    }
                  ]
                },"organizations": {
                  Row: {
                    "arabic_enabled": boolean,"base_currency": string,"created_at": string,"created_by": string | null,"home_country": string,"id": string,"name": string,"slug": string,"updated_at": string
                  }
                  ComputedFields: never
                  Insert: {
                    "arabic_enabled"?: boolean,"base_currency"?: string,"created_at"?: string,"created_by"?: string | null,"home_country"?: string,"id"?: string,"name": string,"slug": string,"updated_at"?: string
                  }
                  Update: {
                    "arabic_enabled"?: boolean,"base_currency"?: string,"created_at"?: string,"created_by"?: string | null,"home_country"?: string,"id"?: string,"name"?: string,"slug"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "organizations_base_currency_fkey"
      columns: ["base_currency"]
isOneToOne: false
      referencedRelation: "currencies"
      referencedColumns: ["code"]
    },{
      foreignKeyName: "organizations_home_country_fkey"
      columns: ["home_country"]
isOneToOne: false
      referencedRelation: "countries"
      referencedColumns: ["code"]
    }
                  ]
                },"public_holidays": {
                  Row: {
                    "country_code": string,"holiday_date": string,"id": number,"kind": string,"name_en": string,"note": string | null,"sector": string,"shifted_from": string | null,"source": string
                  }
                  ComputedFields: never
                  Insert: {
                    "country_code": string,"holiday_date": string,"id"?: never,"kind": string,"name_en": string,"note"?: string | null,"sector": string,"shifted_from"?: string | null,"source": string
                  }
                  Update: {
                    "country_code"?: string,"holiday_date"?: string,"id"?: never,"kind"?: string,"name_en"?: string,"note"?: string | null,"sector"?: string,"shifted_from"?: string | null,"source"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "public_holidays_country_code_fkey"
      columns: ["country_code"]
isOneToOne: false
      referencedRelation: "countries"
      referencedColumns: ["code"]
    }
                  ]
                },"ramadan_windows": {
                  Row: {
                    "arafat_day": string,"country_code": string,"eid_al_adha": string,"eid_al_fitr": string,"hijri_year": number,"ramadan_end": string,"ramadan_start": string,"source": string
                  }
                  ComputedFields: never
                  Insert: {
                    "arafat_day": string,"country_code": string,"eid_al_adha": string,"eid_al_fitr": string,"hijri_year": number,"ramadan_end": string,"ramadan_start": string,"source": string
                  }
                  Update: {
                    "arafat_day"?: string,"country_code"?: string,"eid_al_adha"?: string,"eid_al_fitr"?: string,"hijri_year"?: number,"ramadan_end"?: string,"ramadan_start"?: string,"source"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "ramadan_windows_country_code_fkey"
      columns: ["country_code"]
isOneToOne: false
      referencedRelation: "countries"
      referencedColumns: ["code"]
    }
                  ]
                },"supplier_items": {
                  Row: {
                    "created_at": string,"currency": string,"id": string,"is_preferred": boolean,"item_id": string,"lead_time_days": number,"lead_time_days_p90": number | null,"min_order_quantity": number,"organization_id": string,"pack_size": number,"supplier_id": string,"supplier_part_number": string | null,"unit_price": number,"updated_at": string,"valid_from": string | null
                  }
                  ComputedFields: never
                  Insert: {
                    "created_at"?: string,"currency": string,"id"?: string,"is_preferred"?: boolean,"item_id": string,"lead_time_days": number,"lead_time_days_p90"?: number | null,"min_order_quantity"?: number,"organization_id": string,"pack_size"?: number,"supplier_id": string,"supplier_part_number"?: string | null,"unit_price": number,"updated_at"?: string,"valid_from"?: string | null
                  }
                  Update: {
                    "created_at"?: string,"currency"?: string,"id"?: string,"is_preferred"?: boolean,"item_id"?: string,"lead_time_days"?: number,"lead_time_days_p90"?: number | null,"min_order_quantity"?: number,"organization_id"?: string,"pack_size"?: number,"supplier_id"?: string,"supplier_part_number"?: string | null,"unit_price"?: number,"updated_at"?: string,"valid_from"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "supplier_items_currency_fkey"
      columns: ["currency"]
isOneToOne: false
      referencedRelation: "currencies"
      referencedColumns: ["code"]
    },{
      foreignKeyName: "supplier_items_organization_id_fkey"
      columns: ["organization_id"]
isOneToOne: false
      referencedRelation: "organizations"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "supplier_items_organization_id_item_id_fkey"
      columns: ["organization_id","item_id"]
isOneToOne: false
      referencedRelation: "items"
      referencedColumns: ["organization_id","id"]
    },{
      foreignKeyName: "supplier_items_organization_id_supplier_id_fkey"
      columns: ["organization_id","supplier_id"]
isOneToOne: false
      referencedRelation: "suppliers"
      referencedColumns: ["organization_id","id"]
    }
                  ]
                },"suppliers": {
                  Row: {
                    "code": string,"country_code": string,"created_at": string,"currency": string,"id": string,"is_active": boolean,"lead_time_days_p50": number,"lead_time_days_p90": number,"name_ar": string | null,"name_en": string,"organization_id": string,"updated_at": string
                  }
                  ComputedFields: never
                  Insert: {
                    "code": string,"country_code": string,"created_at"?: string,"currency": string,"id"?: string,"is_active"?: boolean,"lead_time_days_p50": number,"lead_time_days_p90": number,"name_ar"?: string | null,"name_en": string,"organization_id": string,"updated_at"?: string
                  }
                  Update: {
                    "code"?: string,"country_code"?: string,"created_at"?: string,"currency"?: string,"id"?: string,"is_active"?: boolean,"lead_time_days_p50"?: number,"lead_time_days_p90"?: number,"name_ar"?: string | null,"name_en"?: string,"organization_id"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "suppliers_currency_fkey"
      columns: ["currency"]
isOneToOne: false
      referencedRelation: "currencies"
      referencedColumns: ["code"]
    },{
      foreignKeyName: "suppliers_organization_id_fkey"
      columns: ["organization_id"]
isOneToOne: false
      referencedRelation: "organizations"
      referencedColumns: ["id"]
    }
                  ]
                },"user_settings": {
                  Row: {
                    "active_organization_id": string | null,"created_at": string,"updated_at": string,"user_id": string
                  }
                  ComputedFields: never
                  Insert: {
                    "active_organization_id"?: string | null,"created_at"?: string,"updated_at"?: string,"user_id": string
                  }
                  Update: {
                    "active_organization_id"?: string | null,"created_at"?: string,"updated_at"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "user_settings_active_organization_id_fkey"
      columns: ["active_organization_id"]
isOneToOne: false
      referencedRelation: "organizations"
      referencedColumns: ["id"]
    }
                  ]
                }
          }
          Views: {
            [_ in never]: never
          }
          Functions: {
            "accept_invitation":
{ Args: { "p_invitation_id": string }; Returns: string
                           },
"create_organization":
{ Args: { "p_arabic_enabled"?: boolean,"p_base_currency"?: string,"p_home_country"?: string,"p_name": string,"p_slug": string }; Returns: string
                           },
"invite_member":
{ Args: { "p_email": string,"p_organization_id": string,"p_role": string }; Returns: {
              "email": string,"id": string,"resend": boolean
            }[]
                           },
"my_invitations":
{ Args: Record<PropertyKey, never>; Returns: {
              "expires_at": string,"id": string,"invited_by_email": string,"organization_id": string,"organization_name": string,"role": string
            }[]
                           },
"my_organizations":
{ Args: Record<PropertyKey, never>; Returns: {
              "arabic_enabled": boolean,"base_currency": string,"home_country": string,"id": string,"is_active": boolean,"name": string,"role": string,"slug": string
            }[]
                           },
"organization_members":
{ Args: { "p_organization_id": string }; Returns: {
              "created_at": string,"email": string,"location_ids": (string)[],"role": string,"user_id": string
            }[]
                           },
"remove_member":
{ Args: { "p_organization_id": string,"p_user_id": string }; Returns: undefined
                           },
"revoke_invitation":
{ Args: { "p_invitation_id": string }; Returns: undefined
                           },
"set_active_organization":
{ Args: { "p_organization_id": string }; Returns: undefined
                           },
"set_member_locations":
{ Args: { "p_location_ids": (string)[],"p_organization_id": string,"p_user_id": string }; Returns: undefined
                           },
"set_member_role":
{ Args: { "p_organization_id": string,"p_role": string,"p_user_id": string }; Returns: undefined
                           },
"update_organization_settings":
{ Args: { "p_arabic_enabled": boolean,"p_base_currency": string,"p_home_country": string,"p_name": string,"p_organization_id": string }; Returns: undefined
                           }
          }
          Enums: {
            [_ in never]: never
          }
          CompositeTypes: {
            [_ in never]: never
          }
        }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
  ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
      Row: infer R
    }
    ? R
    : never
  : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I
    }
    ? I
    : never
  : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U
    }
    ? U
    : never
  : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
  ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
  : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
  ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
  : never

export const Constants = {
  "public": {
          Enums: {
            
          }
        }
} as const
