// Regenerates packages/shared/src/database.types.ts from the local Supabase stack.
// Usage: pnpm db:types   (requires `pnpm db:start` first)
import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const out = resolve(import.meta.dirname, '../packages/shared/src/database.types.ts')
const types = execSync('pnpm exec supabase gen types --local --schema public', {
  encoding: 'utf8',
  stdio: ['ignore', 'pipe', 'inherit'],
})
const header =
  '// Generated by `pnpm db:types` from the local Supabase schema. Do not edit by hand.\n'
writeFileSync(out, header + types.replace(/\r\n/g, '\n'))
console.log(`wrote ${out}`)
